# Generated by Django 2.0 on 2020-02-24 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
                'managed': True,
            },
        ),
    ]
